### PR TITLE
Switch Schedule 

### PR DESCRIPTION
**Pull request by andrea-mattioli**
Hi i've add the switch to change schedule, example if you have enabled schedule named "test" you'll see switch named switch.blueiris_schedule_test set to "on".
If you want change to schedule named "test2" you need to turn_on switch named switch.blueiris_schedule_test2 and switch.blueiris_schedule_test will be set to off automatically.
I hope I enjoyed it!
Andrea

### CODE REVIEW

**Comment by elad-bar** [comment]
@andrea-mattioli thanks for the contribution, regarding the switch creation - please look at the implementation of the binary_sensors, it should look like that rather same class that "knows" to be profile or schedule based on the type of the ID

**Comment by andrea-mattioli** [comment]
Hi, in the first time i tried to use an index value but the blueiris json
api want the name (string) of the scheduler name.


*Andrea MattioliRed Hat Certified Engineer*
Rhel Consultant
________________________
Mob +39.328/1452201
[image: LinkedIn Andrea Mattioli] <http://it.linkedin.com/in/amattioli2>

**** Riservatezza / Confidentiality ****
In ottemperanza al D.L. n. 196 del 30/6/2003 in materia di protezione dei
dati personali, le informazioni contenute in questo messaggio sono
strettamente riservate ed esclusivamente indirizzate al destinatario
indicato (oppure alla persona responsabile di rimetterlo al destinatario).
Vogliate tener presente che qualsiasi uso, riproduzione o divulgazione di
questo messaggio è vietato. Nel caso in cui aveste ricevuto questo
messaggio per errore, vogliate cortesemente avvertire il mittente e
distruggere il presente messaggio.

According to Italian law D.L. 196/2003 concerning privacy, if you are not
the addressee (or responsible for delivery of the message to such person)
you are hereby notified that any disclosure, reproduction, distribution or
other dissemination or use of this communication is strictly prohibited. If
you have received this message in error, please destroy it and notify us by
email.


Il giorno ven 11 dic 2020 alle ore 12:14 Elad Bar <notifications@github.com>
ha scritto:

**Comment by elad-bar** [comment]
thanks! sorry it took too long

**Comment by andrea-mattioli** [comment]
Thanks you too for your project!!

**Pull request merged**
