### PR TITLE
change camera stream url

### PR DESCRIPTION
**Pull request by mjoshd**
Tested the new url by changing the line in my local copy of the custom component and it works to present the video in Home Assistant as intended.

### CODE REVIEW

**Comment by mjoshd** [comment]
While streaming a camera to a Chromecast by voice command is neat, the `stream:` component in Home Assistant leaves _a lot_ to be desired IMHO. 

The startup delay of the video isn't ideal and the fact that, in a best case scenario, it is on average 10 seconds or more behind real-time is what has kept me away from using it (not to mention the constant buffering and stream failures when sending to Chromecast).

I find it hard to believe that it could be my network or equipment..
All cameras are hardwired
All network infrastructure equipment is Ubiquiti UniFi
All network cables are CAT6
Blue Iris server is an 8th gen i5 and is connected via gigabit
Home Assistant server is also 8th gen i5 and is connected via gigabit
Chromecast #1 is an Ultra and is hardwired using the [included power/ethernet adapter](https://store.google.com/us/product/ethernet_adapter_for_chromecast?hl=en-US)
Chromecast #2 is a 2nd gen unit and is connected to 5GHz, 12 feet away from the AP (UniFi NanoHD)

Both Chromecasts suffer the same playback issues when using the `stream:` component (buffering/stuttering, delay, and eventual failure), however, when playing high bitrate content from YouTube, Plex, etc. they never skip a beat.

I have also tried the 'preload stream' checkbox and, while it does make the video playback start much quicker in Home Assistant, it does nothing to fix the issues which plague streaming to a Chromecast.

If I'm mistaken and this isn't what you or others experience then please let me know.. I'd like for it to work well; in my experience so far it just never has.

While this PR does fix the video playback issue so the `stream:` component will work, I will be [manually creating mjpeg cameras](https://github.com/elad-bar/ha-blueiris/issues/16#issuecomment-541245936) and utilizing those instead (no delay in startup, no buffering, and no failures when sending the video to Chromecast). 

I very much appreciate the time you've put into creating this `custom_component` and hope that the `stream:` component can be vastly improved as to provide an experience equal to that of the mjpeg playback.

**Comment by elad-bar** [comment]
one thing I don't understand, will it work with generic camera or need to switch to MJPEG?
Because if it doesn't work with Generic, switching to MJPEG will be easy

thanks

**Comment by mjoshd** [comment]
The PR does work, as submitted, and keeps it in the Generic Camera format as you originally intended. It just alters the `stream_source:` URL to match what the actual Blue Iris webserver offers up. I found the URL structure in `"C:\Program Files\Blue Iris 5\www\livestream.htm"` on my Blue Iris server.

The problem with reverting to MJPEG is that, as far as I am aware, [mjpeg](https://www.home-assistant.io/integrations/mjpeg/) does not work with the `stream:` component.

In order for `stream:` to work, it has to be one of the various other formats like [ffmpeg](https://www.home-assistant.io/integrations/camera.ffmpeg/), [generic](https://www.home-assistant.io/integrations/generic_ip_camera/), [onvif](https://www.home-assistant.io/integrations/onvif/), etc.

I believe the reason mjpeg doesn't work with `stream:` is that the `stream:` component requires an audio track and mjpeg does not provide one. @[hunterjm](https://github.com/hunterjm) (creator of the `stream:` component) would be able to provide more information.

**Comment by elad-bar** [comment]
Tried to enable the stream with the url you sent, it's not working with the generic camera when opening the camera for preview (didn't manage to stream it as well)
I did find that I missed something with the component, will fix it (same as you sent), but it works only without the stream.

There is a service within the bi component that build YAML for casting using media player play media service, would it work for you?

**Comment by mjoshd** [comment]
I'm closing this PR since the code in your repo has changed and I don't see an easy way to update my fork with your current code... creating a new fork and PR based off your 5c44f69 commit.

**Pull request closed without merging**
