### PR TITLE
Create nb.json

### PR DESCRIPTION
**Pull request by hwikene**
Translation for Norwegian

### CODE REVIEW

**Comment by elad-bar** [comment]
@hwikene  Can you please fix the issue of the json?

Thanks

**Comment by hwikene** [comment]
I cant fix the issue.. dont have access to the code.

**Review by hwikene — COMMENTED** [review]
Fixed missing " :)

**Comment by kramttocs** [comment]
@hwikene Can you push an empty commit to your branch so the checks will be executed again?

**Comment by kramttocs** [comment]
Closing due to failing checks and the age of the pull request.
@hwikene if you want to submit this again, please feel free to do so.

**Pull request closed without merging**
